version: "2"
linters:
  enable:
    - revive
  settings:
    revive:
      rules:
        - name: line-length-limit
          arguments:
            - 140
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: SA1019:.*superceded by feature/s3/transfermanager
      - linters:
          - errcheck
        path: _test\.go
      - linters:
          - revive
        text: line-length-limit
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
