// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

/**
 * CollectionCreate
 */
export type CollectionCreate = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Embedding Model
     */
    embedding_model?: string;
    /**
     * Vector Dim
     */
    vector_dim?: number;
};

/**
 * CommitRequest
 */
export type CommitRequest = {
    /**
     * Collection Id
     */
    collection_id: string;
    /**
     * Content Sha256
     */
    content_sha256: string;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Author
     */
    author?: string | null;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: unknown;
    };
};

/**
 * DocState
 */
export type DocState = 'uploaded' | 'splitting' | 'parsing' | 'embedding' | 'indexing' | 'ready' | 'failed' | 'partial' | 'archived';

/**
 * DocumentOut
 */
export type DocumentOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Collection Id
     */
    collection_id: string | null;
    /**
     * Title
     */
    title: string | null;
    /**
     * Author
     */
    author: string | null;
    /**
     * Page Count
     */
    page_count: number | null;
    /**
     * Byte Size
     */
    byte_size: number | null;
    state: DocState;
    /**
     * Total Shards
     */
    total_shards: number | null;
    /**
     * Shards Done
     */
    shards_done: number;
    /**
     * Shards Failed
     */
    shards_failed: number;
    /**
     * Completeness
     */
    completeness: number | null;
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * KeyCreate
 */
export type KeyCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Scopes
     */
    scopes: Array<string>;
    /**
     * Collections
     */
    collections?: Array<string> | null;
    /**
     * Expires In
     */
    expires_in?: '1d' | '7d' | '30d' | '90d' | 'never';
};

/**
 * KeyCreated
 */
export type KeyCreated = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string | null;
    /**
     * Scopes
     */
    scopes: Array<string> | null;
    /**
     * Collections
     */
    collections: Array<string> | null;
    /**
     * Last Used At
     */
    last_used_at: string | null;
    /**
     * Expires At
     */
    expires_at: string | null;
    /**
     * Revoked At
     */
    revoked_at: string | null;
    /**
     * Raw Key
     */
    raw_key: string;
};

/**
 * KeyOut
 */
export type KeyOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string | null;
    /**
     * Scopes
     */
    scopes: Array<string> | null;
    /**
     * Collections
     */
    collections: Array<string> | null;
    /**
     * Last Used At
     */
    last_used_at: string | null;
    /**
     * Expires At
     */
    expires_at: string | null;
    /**
     * Revoked At
     */
    revoked_at: string | null;
};

/**
 * PresignRequest
 */
export type PresignRequest = {
    /**
     * Collection Id
     */
    collection_id: string;
    /**
     * Byte Size
     */
    byte_size: number;
};

/**
 * PresignResponse
 */
export type PresignResponse = {
    /**
     * Doc Id
     */
    doc_id: string;
    /**
     * Upload Url
     */
    upload_url: string;
};

/**
 * RetryRequest
 */
export type RetryRequest = {
    /**
     * Scope
     */
    scope: string;
};

/**
 * SearchRequest
 */
export type SearchRequest = {
    /**
     * Query
     */
    query: string;
    /**
     * Collection
     */
    collection?: string | null;
    /**
     * Top K
     */
    top_k?: number;
};

/**
 * ShardOut
 */
export type ShardOut = {
    /**
     * Idx
     */
    idx: number;
    /**
     * Page Start
     */
    page_start: number;
    /**
     * Page End
     */
    page_end: number;
    /**
     * State
     */
    state: string;
    /**
     * Attempts
     */
    attempts: number;
    /**
     * Needs Ocr
     */
    needs_ocr: boolean;
    /**
     * Duration Ms
     */
    duration_ms: number | null;
    /**
     * Peak Rss Mb
     */
    peak_rss_mb: number | null;
    /**
     * Error Code
     */
    error_code: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type PresignV1DocumentsPresignPostData = {
    body: PresignRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/documents/presign';
};

export type PresignV1DocumentsPresignPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PresignV1DocumentsPresignPostError = PresignV1DocumentsPresignPostErrors[keyof PresignV1DocumentsPresignPostErrors];

export type PresignV1DocumentsPresignPostResponses = {
    /**
     * Successful Response
     */
    200: PresignResponse;
};

export type PresignV1DocumentsPresignPostResponse = PresignV1DocumentsPresignPostResponses[keyof PresignV1DocumentsPresignPostResponses];

export type CommitV1DocumentsDocIdCommitPostData = {
    body: CommitRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Doc Id
         */
        doc_id: string;
    };
    query?: never;
    url: '/v1/documents/{doc_id}/commit';
};

export type CommitV1DocumentsDocIdCommitPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CommitV1DocumentsDocIdCommitPostError = CommitV1DocumentsDocIdCommitPostErrors[keyof CommitV1DocumentsDocIdCommitPostErrors];

export type CommitV1DocumentsDocIdCommitPostResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type ListDocumentsV1DocumentsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * State
         */
        state?: DocState | null;
        /**
         * Collection
         */
        collection?: string | null;
        /**
         * Q
         */
        q?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/v1/documents';
};

export type ListDocumentsV1DocumentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListDocumentsV1DocumentsGetError = ListDocumentsV1DocumentsGetErrors[keyof ListDocumentsV1DocumentsGetErrors];

export type ListDocumentsV1DocumentsGetResponses = {
    /**
     * Response List Documents V1 Documents Get
     *
     * Successful Response
     */
    200: Array<DocumentOut>;
};

export type ListDocumentsV1DocumentsGetResponse = ListDocumentsV1DocumentsGetResponses[keyof ListDocumentsV1DocumentsGetResponses];

export type GetDocumentV1DocumentsDocIdGetData = {
    body?: never;
    path: {
        /**
         * Doc Id
         */
        doc_id: string;
    };
    query?: never;
    url: '/v1/documents/{doc_id}';
};

export type GetDocumentV1DocumentsDocIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDocumentV1DocumentsDocIdGetError = GetDocumentV1DocumentsDocIdGetErrors[keyof GetDocumentV1DocumentsDocIdGetErrors];

export type GetDocumentV1DocumentsDocIdGetResponses = {
    /**
     * Successful Response
     */
    200: DocumentOut;
};

export type GetDocumentV1DocumentsDocIdGetResponse = GetDocumentV1DocumentsDocIdGetResponses[keyof GetDocumentV1DocumentsDocIdGetResponses];

export type GetShardsV1DocumentsDocIdShardsGetData = {
    body?: never;
    path: {
        /**
         * Doc Id
         */
        doc_id: string;
    };
    query?: never;
    url: '/v1/documents/{doc_id}/shards';
};

export type GetShardsV1DocumentsDocIdShardsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetShardsV1DocumentsDocIdShardsGetError = GetShardsV1DocumentsDocIdShardsGetErrors[keyof GetShardsV1DocumentsDocIdShardsGetErrors];

export type GetShardsV1DocumentsDocIdShardsGetResponses = {
    /**
     * Response Get Shards V1 Documents  Doc Id  Shards Get
     *
     * Successful Response
     */
    200: Array<ShardOut>;
};

export type GetShardsV1DocumentsDocIdShardsGetResponse = GetShardsV1DocumentsDocIdShardsGetResponses[keyof GetShardsV1DocumentsDocIdShardsGetResponses];

export type RetryV1DocumentsDocIdRetryPostData = {
    body: RetryRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Doc Id
         */
        doc_id: string;
    };
    query?: never;
    url: '/v1/documents/{doc_id}/retry';
};

export type RetryV1DocumentsDocIdRetryPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RetryV1DocumentsDocIdRetryPostError = RetryV1DocumentsDocIdRetryPostErrors[keyof RetryV1DocumentsDocIdRetryPostErrors];

export type RetryV1DocumentsDocIdRetryPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListCollectionsV1CollectionsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/collections';
};

export type ListCollectionsV1CollectionsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateCollectionV1CollectionsPostData = {
    body: CollectionCreate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/collections';
};

export type CreateCollectionV1CollectionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCollectionV1CollectionsPostError = CreateCollectionV1CollectionsPostErrors[keyof CreateCollectionV1CollectionsPostErrors];

export type CreateCollectionV1CollectionsPostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type CollectionStatsV1CollectionsCollectionIdStatsGetData = {
    body?: never;
    path: {
        /**
         * Collection Id
         */
        collection_id: string;
    };
    query?: never;
    url: '/v1/collections/{collection_id}/stats';
};

export type CollectionStatsV1CollectionsCollectionIdStatsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CollectionStatsV1CollectionsCollectionIdStatsGetError = CollectionStatsV1CollectionsCollectionIdStatsGetErrors[keyof CollectionStatsV1CollectionsCollectionIdStatsGetErrors];

export type CollectionStatsV1CollectionsCollectionIdStatsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SearchV1SearchPostData = {
    body: SearchRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/search';
};

export type SearchV1SearchPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchV1SearchPostError = SearchV1SearchPostErrors[keyof SearchV1SearchPostErrors];

export type SearchV1SearchPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListKeysV1KeysGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/keys';
};

export type ListKeysV1KeysGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListKeysV1KeysGetError = ListKeysV1KeysGetErrors[keyof ListKeysV1KeysGetErrors];

export type ListKeysV1KeysGetResponses = {
    /**
     * Response List Keys V1 Keys Get
     *
     * Successful Response
     */
    200: Array<KeyOut>;
};

export type ListKeysV1KeysGetResponse = ListKeysV1KeysGetResponses[keyof ListKeysV1KeysGetResponses];

export type CreateKeyV1KeysPostData = {
    body: KeyCreate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/keys';
};

export type CreateKeyV1KeysPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateKeyV1KeysPostError = CreateKeyV1KeysPostErrors[keyof CreateKeyV1KeysPostErrors];

export type CreateKeyV1KeysPostResponses = {
    /**
     * Successful Response
     */
    201: KeyCreated;
};

export type CreateKeyV1KeysPostResponse = CreateKeyV1KeysPostResponses[keyof CreateKeyV1KeysPostResponses];

export type RevokeKeyV1KeysKeyIdRevokePostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Key Id
         */
        key_id: string;
    };
    query?: never;
    url: '/v1/keys/{key_id}/revoke';
};

export type RevokeKeyV1KeysKeyIdRevokePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeKeyV1KeysKeyIdRevokePostError = RevokeKeyV1KeysKeyIdRevokePostErrors[keyof RevokeKeyV1KeysKeyIdRevokePostErrors];

export type RevokeKeyV1KeysKeyIdRevokePostResponses = {
    /**
     * Successful Response
     */
    200: KeyOut;
};

export type RevokeKeyV1KeysKeyIdRevokePostResponse = RevokeKeyV1KeysKeyIdRevokePostResponses[keyof RevokeKeyV1KeysKeyIdRevokePostResponses];

export type UsageSummaryV1UsageSummaryGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Period
         */
        period?: 'today' | '24h' | '7d' | '30d';
    };
    url: '/v1/usage/summary';
};

export type UsageSummaryV1UsageSummaryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsageSummaryV1UsageSummaryGetError = UsageSummaryV1UsageSummaryGetErrors[keyof UsageSummaryV1UsageSummaryGetErrors];

export type UsageSummaryV1UsageSummaryGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListEventsV1EventsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Doc Id
         */
        doc_id?: string | null;
        /**
         * Level
         */
        level?: string | null;
        /**
         * Stage
         */
        stage?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/v1/events';
};

export type ListEventsV1EventsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListEventsV1EventsGetError = ListEventsV1EventsGetErrors[keyof ListEventsV1EventsGetErrors];

export type ListEventsV1EventsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type EventStreamV1EventsStreamGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Poll S
         */
        poll_s?: number;
    };
    url: '/v1/events/stream';
};

export type EventStreamV1EventsStreamGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EventStreamV1EventsStreamGetError = EventStreamV1EventsStreamGetErrors[keyof EventStreamV1EventsStreamGetErrors];

export type EventStreamV1EventsStreamGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthV1SystemHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/system/health';
};

export type HealthV1SystemHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type QueuesV1SystemQueuesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/system/queues';
};

export type QueuesV1SystemQueuesGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PipelineV1SystemPipelineGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/system/pipeline';
};

export type PipelineV1SystemPipelineGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMetricsV1SystemMetricsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/system/metrics';
};

export type GetMetricsV1SystemMetricsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
