// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

/**
 * CollectionCreate
 */
export type CollectionCreate = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Embedding Model Id
     */
    embedding_model_id: string;
};

/**
 * CommitRequest
 */
export type CommitRequest = {
    /**
     * Collection Id
     */
    collection_id: string;
    /**
     * Content Sha256
     */
    content_sha256: string;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Author
     */
    author?: string | null;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: unknown;
    };
};

/**
 * DocState
 */
export type DocState = 'uploaded' | 'splitting' | 'parsing' | 'embedding' | 'indexing' | 'ready' | 'failed' | 'partial' | 'archived';

/**
 * DocumentOut
 */
export type DocumentOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Collection Id
     */
    collection_id: string | null;
    /**
     * Title
     */
    title: string | null;
    /**
     * Author
     */
    author: string | null;
    /**
     * Page Count
     */
    page_count: number | null;
    /**
     * Byte Size
     */
    byte_size: number | null;
    state: DocState;
    /**
     * Total Shards
     */
    total_shards: number | null;
    /**
     * Shards Done
     */
    shards_done: number;
    /**
     * Shards Failed
     */
    shards_failed: number;
    /**
     * Completeness
     */
    completeness: number | null;
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * KeyCreate
 */
export type KeyCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Scopes
     */
    scopes: Array<string>;
    /**
     * Collections
     */
    collections?: Array<string> | null;
    /**
     * Expires In
     */
    expires_in?: '1d' | '7d' | '30d' | '90d' | 'never';
};

/**
 * KeyCreated
 */
export type KeyCreated = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string | null;
    /**
     * Scopes
     */
    scopes: Array<string> | null;
    /**
     * Collections
     */
    collections: Array<string> | null;
    /**
     * Last Used At
     */
    last_used_at: string | null;
    /**
     * Expires At
     */
    expires_at: string | null;
    /**
     * Revoked At
     */
    revoked_at: string | null;
    /**
     * Raw Key
     */
    raw_key: string;
};

/**
 * KeyOut
 */
export type KeyOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string | null;
    /**
     * Scopes
     */
    scopes: Array<string> | null;
    /**
     * Collections
     */
    collections: Array<string> | null;
    /**
     * Last Used At
     */
    last_used_at: string | null;
    /**
     * Expires At
     */
    expires_at: string | null;
    /**
     * Revoked At
     */
    revoked_at: string | null;
};

/**
 * PresignRequest
 */
export type PresignRequest = {
    /**
     * Collection Id
     */
    collection_id: string;
    /**
     * Byte Size
     */
    byte_size: number;
};

/**
 * PresignResponse
 */
export type PresignResponse = {
    /**
     * Doc Id
     */
    doc_id: string;
    /**
     * Upload Url
     */
    upload_url: string;
};

/**
 * RetryRequest
 */
export type RetryRequest = {
    /**
     * Scope
     */
    scope: string;
};

/**
 * SearchRequest
 */
export type SearchRequest = {
    /**
     * Query
     */
    query: string;
    /**
     * Collection
     */
    collection?: string | null;
    /**
     * Collections
     *
     * Multi-collection search: grouped by bound embedding model, fused with RRF
     */
    collections?: Array<string>;
    /**
     * Top K
     */
    top_k?: number;
    /**
     * Rerank
     *
     * Re-score the candidate pool with the configured cross-encoder reranker
     */
    rerank?: boolean | null;
    /**
     * Rerank Model Id
     *
     * Explicit reranker registry id — overrides the collection's bound reranker
     */
    rerank_model_id?: string | null;
    /**
     * Metadata Filter
     *
     * Document-level filter: {"author"} (case-insensitive), {"year_from"/"year_to"} (metadata year range), other keys match metadata->>key exactly
     */
    metadata_filter?: {
        [key: string]: unknown;
    };
};

/**
 * ShardOut
 */
export type ShardOut = {
    /**
     * Idx
     */
    idx: number;
    /**
     * Page Start
     */
    page_start: number;
    /**
     * Page End
     */
    page_end: number;
    /**
     * State
     */
    state: string;
    /**
     * Attempts
     */
    attempts: number;
    /**
     * Needs Ocr
     */
    needs_ocr: boolean;
    /**
     * Duration Ms
     */
    duration_ms: number | null;
    /**
     * Peak Rss Mb
     */
    peak_rss_mb: number | null;
    /**
     * Error Code
     */
    error_code: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * ModelOut
 */
export type ModelOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Provider
     */
    provider: 'tei' | 'ollama' | 'openai';
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Ingest Url
     */
    ingest_url: string;
    /**
     * Query Url
     */
    query_url: string;
    /**
     * Has Api Key
     */
    has_api_key?: boolean;
    /**
     * Vector Dim
     */
    vector_dim: number;
    /**
     * Query Prefix
     */
    query_prefix?: string;
    /**
     * Batch Size
     */
    batch_size?: number;
    /**
     * Ctx Budget
     */
    ctx_budget?: number;
    /**
     * Truncate Chars
     */
    truncate_chars?: number;
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Updated At
     */
    updated_at?: string;
};

/**
 * ModelCreate
 */
export type ModelCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Provider
     */
    provider: 'tei' | 'ollama' | 'openai';
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Ingest Url
     */
    ingest_url: string;
    /**
     * Query Url
     */
    query_url: string;
    /**
     * Api Key
     */
    api_key?: string | null;
    /**
     * Vector Dim
     */
    vector_dim: number;
    /**
     * Query Prefix
     */
    query_prefix?: string;
    /**
     * Batch Size
     */
    batch_size?: number;
    /**
     * Ctx Budget
     */
    ctx_budget?: number;
    /**
     * Truncate Chars
     */
    truncate_chars?: number;
};

/**
 * ModelUpdate
 */
export type ModelUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Provider
     */
    provider?: 'tei' | 'ollama' | 'openai' | null;
    /**
     * Model Id
     */
    model_id?: string | null;
    /**
     * Ingest Url
     */
    ingest_url?: string | null;
    /**
     * Query Url
     */
    query_url?: string | null;
    /**
     * Api Key
     *
     * null = unchanged
     */
    api_key?: string | null;
    /**
     * Vector Dim
     */
    vector_dim?: number | null;
    /**
     * Query Prefix
     */
    query_prefix?: string | null;
    /**
     * Batch Size
     */
    batch_size?: number | null;
    /**
     * Ctx Budget
     */
    ctx_budget?: number | null;
    /**
     * Truncate Chars
     */
    truncate_chars?: number | null;
};

/**
 * ModelTestResult
 */
export type ModelTestResult = {
    /**
     * Reachable
     */
    reachable: boolean;
    /**
     * Latency Ms
     */
    latency_ms?: number | null;
    /**
     * Detail
     */
    detail: string;
    /**
     * Vector Dim
     */
    vector_dim?: number | null;
};

/**
 * FetchUrlRequest
 */
export type FetchUrlRequest = {
    /**
     * Collection Id
     */
    collection_id: string;
    /**
     * Url
     */
    url: string;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Author
     */
    author?: string | null;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: unknown;
    };
};

/**
 * OpdsAcqLink
 */
export type OpdsAcqLink = {
    /**
     * Href
     */
    href?: string;
    /**
     * Mime Type
     */
    mime_type?: string;
};

/**
 * OpdsEntry
 */
export type OpdsEntry = {
    /**
     * Title
     */
    title: string;
    /**
     * Authors
     */
    authors: Array<string>;
    /**
     * Summary
     */
    summary?: string;
    /**
     * Acquisition
     */
    acquisition: Array<OpdsAcqLink>;
};

/**
 * OpdsBrowseRequest
 */
export type OpdsBrowseRequest = {
    /**
     * Url
     */
    url: string;
    /**
     * Username
     */
    username?: string;
    /**
     * Password
     */
    password?: string;
    /**
     * Feed Url
     */
    feed_url?: string;
};

/**
 * OpdsBrowseResult
 */
export type OpdsBrowseResult = {
    /**
     * Entries
     */
    entries: Array<OpdsEntry>;
    /**
     * Next Href
     */
    next_href?: string | null;
};

/**
 * OpdsEntryRef
 */
export type OpdsEntryRef = {
    /**
     * Title
     */
    title?: string;
    /**
     * Href
     */
    href?: string;
    /**
     * Mime Type
     */
    mime_type?: string;
};

/**
 * OpdsSyncRequest
 */
export type OpdsSyncRequest = {
    /**
     * Url
     */
    url: string;
    /**
     * Username
     */
    username?: string;
    /**
     * Password
     */
    password?: string;
    /**
     * Collection Id
     */
    collection_id: string;
    /**
     * Selection
     */
    selection?: Array<OpdsEntryRef>;
};

/**
 * OpdsItemResult
 */
export type OpdsItemResult = {
    /**
     * Title
     */
    title: string;
    /**
     * Status
     */
    status: 'accepted' | 'duplicate' | 'rejected';
    /**
     * Doc Id
     */
    doc_id?: string | null;
    /**
     * Detail
     */
    detail?: string | null;
};

/**
 * OpdsSyncResult
 */
export type OpdsSyncResult = {
    /**
     * Synced
     */
    synced: number;
    /**
     * Failed
     */
    failed: number;
    /**
     * Results
     */
    results: Array<OpdsItemResult>;
};

/**
 * RerankModelOut
 */
export type RerankModelOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Provider
     */
    provider: 'tei' | 'openai';
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Query Url
     */
    query_url: string;
    /**
     * Has Api Key
     */
    has_api_key?: boolean;
    /**
     * Truncate Chars
     */
    truncate_chars?: number;
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Updated At
     */
    updated_at?: string;
};

/**
 * RerankModelCreate
 */
export type RerankModelCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Provider
     */
    provider: 'tei' | 'openai';
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Query Url
     */
    query_url: string;
    /**
     * Api Key
     */
    api_key?: string | null;
    /**
     * Truncate Chars
     */
    truncate_chars?: number;
};

/**
 * RerankModelUpdate
 */
export type RerankModelUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Provider
     */
    provider?: 'tei' | 'openai' | null;
    /**
     * Model Id
     */
    model_id?: string | null;
    /**
     * Query Url
     */
    query_url?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
    /**
     * Truncate Chars
     */
    truncate_chars?: number | null;
};

/**
 * RerankTestResult
 */
export type RerankTestResult = {
    /**
     * Reachable
     */
    reachable: boolean;
    /**
     * Latency Ms
     */
    latency_ms?: number | null;
    /**
     * Detail
     */
    detail: string;
};

/**
 * CollectionRerankerBind
 */
export type CollectionRerankerBind = {
    /**
     * Rerank Model Id
     *
     * null clears the binding
     */
    rerank_model_id?: string | null;
};

/**
 * ChunkOut
 */
export type ChunkOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Seq
     */
    seq: number;
    /**
     * Is Parent
     */
    is_parent: boolean;
    /**
     * Parent Id
     */
    parent_id?: string | null;
    /**
     * Page Start
     */
    page_start?: number | null;
    /**
     * Page End
     */
    page_end?: number | null;
    /**
     * Heading Path
     */
    heading_path?: Array<string>;
    /**
     * Header Breadcrumb
     */
    header_breadcrumb?: string | null;
    /**
     * Text
     */
    text: string;
    /**
     * Token Count
     */
    token_count: number;
    /**
     * Embedded At
     */
    embedded_at?: string | null;
};

/**
 * ChunkList
 */
export type ChunkList = {
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Chunks
     */
    chunks: Array<ChunkOut>;
};

/**
 * ChunkDetail
 */
export type ChunkDetail = {
    /**
     * Id
     */
    id?: string;
    /**
     * Seq
     */
    seq?: number;
    /**
     * Is Parent
     */
    is_parent?: boolean;
    /**
     * Parent Id
     */
    parent_id?: string | null;
    /**
     * Page Start
     */
    page_start?: number | null;
    /**
     * Page End
     */
    page_end?: number | null;
    /**
     * Heading Path
     */
    heading_path?: Array<string>;
    /**
     * Header Breadcrumb
     */
    header_breadcrumb?: string | null;
    /**
     * Text
     */
    text?: string;
    /**
     * Token Count
     */
    token_count?: number;
    /**
     * Embedded At
     */
    embedded_at?: string | null;
    /**
     * Parent Text
     */
    parent_text?: string;
    /**
     * Prev Id
     */
    prev_id?: string | null;
    /**
     * Next Id
     */
    next_id?: string | null;
    /**
     * Neighbours
     */
    neighbours?: Array<ChunkOut>;
};

export type PresignV1DocumentsPresignPostData = {
    body: PresignRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/documents/presign';
};

export type PresignV1DocumentsPresignPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PresignV1DocumentsPresignPostError = PresignV1DocumentsPresignPostErrors[keyof PresignV1DocumentsPresignPostErrors];

export type PresignV1DocumentsPresignPostResponses = {
    /**
     * Successful Response
     */
    200: PresignResponse;
};

export type PresignV1DocumentsPresignPostResponse = PresignV1DocumentsPresignPostResponses[keyof PresignV1DocumentsPresignPostResponses];

export type CommitV1DocumentsDocIdCommitPostData = {
    body: CommitRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Doc Id
         */
        doc_id: string;
    };
    query?: never;
    url: '/v1/documents/{doc_id}/commit';
};

export type CommitV1DocumentsDocIdCommitPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CommitV1DocumentsDocIdCommitPostError = CommitV1DocumentsDocIdCommitPostErrors[keyof CommitV1DocumentsDocIdCommitPostErrors];

export type CommitV1DocumentsDocIdCommitPostResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type ListDocumentsV1DocumentsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * State
         */
        state?: DocState | null;
        /**
         * Collection
         */
        collection?: string | null;
        /**
         * Q
         */
        q?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/v1/documents';
};

export type ListDocumentsV1DocumentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListDocumentsV1DocumentsGetError = ListDocumentsV1DocumentsGetErrors[keyof ListDocumentsV1DocumentsGetErrors];

export type ListDocumentsV1DocumentsGetResponses = {
    /**
     * Response List Documents V1 Documents Get
     *
     * Successful Response
     */
    200: Array<DocumentOut>;
};

export type ListDocumentsV1DocumentsGetResponse = ListDocumentsV1DocumentsGetResponses[keyof ListDocumentsV1DocumentsGetResponses];

export type GetDocumentV1DocumentsDocIdGetData = {
    body?: never;
    path: {
        /**
         * Doc Id
         */
        doc_id: string;
    };
    query?: never;
    url: '/v1/documents/{doc_id}';
};

export type GetDocumentV1DocumentsDocIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDocumentV1DocumentsDocIdGetError = GetDocumentV1DocumentsDocIdGetErrors[keyof GetDocumentV1DocumentsDocIdGetErrors];

export type GetDocumentV1DocumentsDocIdGetResponses = {
    /**
     * Successful Response
     */
    200: DocumentOut;
};

export type GetDocumentV1DocumentsDocIdGetResponse = GetDocumentV1DocumentsDocIdGetResponses[keyof GetDocumentV1DocumentsDocIdGetResponses];

export type GetShardsV1DocumentsDocIdShardsGetData = {
    body?: never;
    path: {
        /**
         * Doc Id
         */
        doc_id: string;
    };
    query?: never;
    url: '/v1/documents/{doc_id}/shards';
};

export type GetShardsV1DocumentsDocIdShardsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetShardsV1DocumentsDocIdShardsGetError = GetShardsV1DocumentsDocIdShardsGetErrors[keyof GetShardsV1DocumentsDocIdShardsGetErrors];

export type GetShardsV1DocumentsDocIdShardsGetResponses = {
    /**
     * Response Get Shards V1 Documents  Doc Id  Shards Get
     *
     * Successful Response
     */
    200: Array<ShardOut>;
};

export type GetShardsV1DocumentsDocIdShardsGetResponse = GetShardsV1DocumentsDocIdShardsGetResponses[keyof GetShardsV1DocumentsDocIdShardsGetResponses];

export type RetryV1DocumentsDocIdRetryPostData = {
    body: RetryRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Doc Id
         */
        doc_id: string;
    };
    query?: never;
    url: '/v1/documents/{doc_id}/retry';
};

export type RetryV1DocumentsDocIdRetryPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RetryV1DocumentsDocIdRetryPostError = RetryV1DocumentsDocIdRetryPostErrors[keyof RetryV1DocumentsDocIdRetryPostErrors];

export type RetryV1DocumentsDocIdRetryPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListCollectionsV1CollectionsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/collections';
};

export type ListCollectionsV1CollectionsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateCollectionV1CollectionsPostData = {
    body: CollectionCreate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/collections';
};

export type CreateCollectionV1CollectionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCollectionV1CollectionsPostError = CreateCollectionV1CollectionsPostErrors[keyof CreateCollectionV1CollectionsPostErrors];

export type CreateCollectionV1CollectionsPostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type CollectionStatsV1CollectionsCollectionIdStatsGetData = {
    body?: never;
    path: {
        /**
         * Collection Id
         */
        collection_id: string;
    };
    query?: never;
    url: '/v1/collections/{collection_id}/stats';
};

export type CollectionStatsV1CollectionsCollectionIdStatsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CollectionStatsV1CollectionsCollectionIdStatsGetError = CollectionStatsV1CollectionsCollectionIdStatsGetErrors[keyof CollectionStatsV1CollectionsCollectionIdStatsGetErrors];

export type CollectionStatsV1CollectionsCollectionIdStatsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SearchV1SearchPostData = {
    body: SearchRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/search';
};

export type SearchV1SearchPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchV1SearchPostError = SearchV1SearchPostErrors[keyof SearchV1SearchPostErrors];

export type SearchV1SearchPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListKeysV1KeysGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/keys';
};

export type ListKeysV1KeysGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListKeysV1KeysGetError = ListKeysV1KeysGetErrors[keyof ListKeysV1KeysGetErrors];

export type ListKeysV1KeysGetResponses = {
    /**
     * Response List Keys V1 Keys Get
     *
     * Successful Response
     */
    200: Array<KeyOut>;
};

export type ListKeysV1KeysGetResponse = ListKeysV1KeysGetResponses[keyof ListKeysV1KeysGetResponses];

export type CreateKeyV1KeysPostData = {
    body: KeyCreate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/keys';
};

export type CreateKeyV1KeysPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateKeyV1KeysPostError = CreateKeyV1KeysPostErrors[keyof CreateKeyV1KeysPostErrors];

export type CreateKeyV1KeysPostResponses = {
    /**
     * Successful Response
     */
    201: KeyCreated;
};

export type CreateKeyV1KeysPostResponse = CreateKeyV1KeysPostResponses[keyof CreateKeyV1KeysPostResponses];

export type RevokeKeyV1KeysKeyIdRevokePostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Key Id
         */
        key_id: string;
    };
    query?: never;
    url: '/v1/keys/{key_id}/revoke';
};

export type RevokeKeyV1KeysKeyIdRevokePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeKeyV1KeysKeyIdRevokePostError = RevokeKeyV1KeysKeyIdRevokePostErrors[keyof RevokeKeyV1KeysKeyIdRevokePostErrors];

export type RevokeKeyV1KeysKeyIdRevokePostResponses = {
    /**
     * Successful Response
     */
    200: KeyOut;
};

export type RevokeKeyV1KeysKeyIdRevokePostResponse = RevokeKeyV1KeysKeyIdRevokePostResponses[keyof RevokeKeyV1KeysKeyIdRevokePostResponses];

export type UsageSummaryV1UsageSummaryGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Period
         */
        period?: 'today' | '24h' | '7d' | '30d';
    };
    url: '/v1/usage/summary';
};

export type UsageSummaryV1UsageSummaryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsageSummaryV1UsageSummaryGetError = UsageSummaryV1UsageSummaryGetErrors[keyof UsageSummaryV1UsageSummaryGetErrors];

export type UsageSummaryV1UsageSummaryGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListEventsV1EventsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Doc Id
         */
        doc_id?: string | null;
        /**
         * Level
         */
        level?: string | null;
        /**
         * Stage
         */
        stage?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/v1/events';
};

export type ListEventsV1EventsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListEventsV1EventsGetError = ListEventsV1EventsGetErrors[keyof ListEventsV1EventsGetErrors];

export type ListEventsV1EventsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type EventStreamV1EventsStreamGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Poll S
         */
        poll_s?: number;
    };
    url: '/v1/events/stream';
};

export type EventStreamV1EventsStreamGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EventStreamV1EventsStreamGetError = EventStreamV1EventsStreamGetErrors[keyof EventStreamV1EventsStreamGetErrors];

export type EventStreamV1EventsStreamGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthV1SystemHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/system/health';
};

export type HealthV1SystemHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type QueuesV1SystemQueuesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/system/queues';
};

export type QueuesV1SystemQueuesGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PipelineV1SystemPipelineGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/system/pipeline';
};

export type PipelineV1SystemPipelineGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMetricsV1SystemMetricsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/system/metrics';
};

export type GetMetricsV1SystemMetricsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListModelsV1ModelsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/models';
};

export type ListModelsV1ModelsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListModelsV1ModelsGetError = ListModelsV1ModelsGetErrors[keyof ListModelsV1ModelsGetErrors];

export type ListModelsV1ModelsGetResponses = {
    /**
     * Successful Response
     */
    200: ModelOut;
};

export type ListModelsV1ModelsGetResponse = ListModelsV1ModelsGetResponses[keyof ListModelsV1ModelsGetResponses];

export type CreateModelV1ModelsPostData = {
    body: ModelCreate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/models';
};

export type CreateModelV1ModelsPostErrors = {
    /**
     * Duplicate name
     */
    409: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateModelV1ModelsPostError = CreateModelV1ModelsPostErrors[keyof CreateModelV1ModelsPostErrors];

export type CreateModelV1ModelsPostResponses = {
    /**
     * Successful Response
     */
    201: ModelOut;
};

export type CreateModelV1ModelsPostResponse = CreateModelV1ModelsPostResponses[keyof CreateModelV1ModelsPostResponses];

export type TestModelV1ModelsTestPostData = {
    body: ModelCreate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/models/test';
};

export type TestModelV1ModelsTestPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestModelV1ModelsTestPostError = TestModelV1ModelsTestPostErrors[keyof TestModelV1ModelsTestPostErrors];

export type TestModelV1ModelsTestPostResponses = {
    /**
     * Successful Response
     */
    200: ModelTestResult;
};

export type TestModelV1ModelsTestPostResponse = TestModelV1ModelsTestPostResponses[keyof TestModelV1ModelsTestPostResponses];

export type DeleteModelV1ModelsModelIdDeleteData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/models/{model_id}';
};

export type DeleteModelV1ModelsModelIdDeleteErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Bound or default
     */
    409: unknown;
};

export type DeleteModelV1ModelsModelIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteModelV1ModelsModelIdDeleteResponse = DeleteModelV1ModelsModelIdDeleteResponses[keyof DeleteModelV1ModelsModelIdDeleteResponses];

export type UpdateModelV1ModelsModelIdPostData = {
    body: ModelUpdate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/models/{model_id}';
};

export type UpdateModelV1ModelsModelIdPostErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Name clash
     */
    409: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateModelV1ModelsModelIdPostError = UpdateModelV1ModelsModelIdPostErrors[keyof UpdateModelV1ModelsModelIdPostErrors];

export type UpdateModelV1ModelsModelIdPostResponses = {
    /**
     * Successful Response
     */
    200: ModelOut;
};

export type UpdateModelV1ModelsModelIdPostResponse = UpdateModelV1ModelsModelIdPostResponses[keyof UpdateModelV1ModelsModelIdPostResponses];

export type BindCollectionModelV1CollectionsCollectionIdModelPostData = {
    body: ModelCreate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/collections/{collection_id}/model';
};

export type BindCollectionModelV1CollectionsCollectionIdModelPostErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BindCollectionModelV1CollectionsCollectionIdModelPostError = BindCollectionModelV1CollectionsCollectionIdModelPostErrors[keyof BindCollectionModelV1CollectionsCollectionIdModelPostErrors];

export type BindCollectionModelV1CollectionsCollectionIdModelPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type FetchUrlV1DocumentsFetchUrlPostData = {
    body: FetchUrlRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/documents/fetch-url';
};

export type FetchUrlV1DocumentsFetchUrlPostErrors = {
    /**
     * Fetch/verify failure
     */
    400: unknown;
    /**
     * Duplicate
     */
    409: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Backlog
     */
    429: unknown;
};

export type FetchUrlV1DocumentsFetchUrlPostError = FetchUrlV1DocumentsFetchUrlPostErrors[keyof FetchUrlV1DocumentsFetchUrlPostErrors];

export type FetchUrlV1DocumentsFetchUrlPostResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type OpdsBrowseV1ConnectorsOpdsBrowsePostData = {
    body: OpdsBrowseRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/connectors/opds/browse';
};

export type OpdsBrowseV1ConnectorsOpdsBrowsePostErrors = {
    /**
     * Bad credentials or not Atom
     */
    400: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OpdsBrowseV1ConnectorsOpdsBrowsePostError = OpdsBrowseV1ConnectorsOpdsBrowsePostErrors[keyof OpdsBrowseV1ConnectorsOpdsBrowsePostErrors];

export type OpdsBrowseV1ConnectorsOpdsBrowsePostResponses = {
    /**
     * Successful Response
     */
    200: OpdsBrowseResult;
};

export type OpdsBrowseV1ConnectorsOpdsBrowsePostResponse = OpdsBrowseV1ConnectorsOpdsBrowsePostResponses[keyof OpdsBrowseV1ConnectorsOpdsBrowsePostResponses];

export type OpdsSyncV1ConnectorsOpdsSyncPostData = {
    body: OpdsSyncRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/connectors/opds/sync';
};

export type OpdsSyncV1ConnectorsOpdsSyncPostErrors = {
    /**
     * Bad credentials
     */
    400: unknown;
    /**
     * Collection not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OpdsSyncV1ConnectorsOpdsSyncPostError = OpdsSyncV1ConnectorsOpdsSyncPostErrors[keyof OpdsSyncV1ConnectorsOpdsSyncPostErrors];

export type OpdsSyncV1ConnectorsOpdsSyncPostResponses = {
    /**
     * Successful Response
     */
    200: OpdsSyncResult;
};

export type OpdsSyncV1ConnectorsOpdsSyncPostResponse = OpdsSyncV1ConnectorsOpdsSyncPostResponses[keyof OpdsSyncV1ConnectorsOpdsSyncPostResponses];

export type ListRerankModelsV1RerankModelsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/rerank-models';
};

export type ListRerankModelsV1RerankModelsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRerankModelsV1RerankModelsGetError = ListRerankModelsV1RerankModelsGetErrors[keyof ListRerankModelsV1RerankModelsGetErrors];

export type ListRerankModelsV1RerankModelsGetResponses = {
    /**
     * Successful Response
     */
    200: Array<RerankModelOut>;
};

export type ListRerankModelsV1RerankModelsGetResponse = ListRerankModelsV1RerankModelsGetResponses[keyof ListRerankModelsV1RerankModelsGetResponses];

export type CreateRerankModelV1RerankModelsPostData = {
    body: RerankModelCreate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/rerank-models';
};

export type CreateRerankModelV1RerankModelsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRerankModelV1RerankModelsPostError = CreateRerankModelV1RerankModelsPostErrors[keyof CreateRerankModelV1RerankModelsPostErrors];

export type CreateRerankModelV1RerankModelsPostResponses = {
    /**
     * Successful Response
     */
    200: RerankModelOut;
};

export type CreateRerankModelV1RerankModelsPostResponse = CreateRerankModelV1RerankModelsPostResponses[keyof CreateRerankModelV1RerankModelsPostResponses];

export type TestRerankModelV1RerankModelsTestPostData = {
    body: RerankModelCreate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/rerank-models/test';
};

export type TestRerankModelV1RerankModelsTestPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestRerankModelV1RerankModelsTestPostError = TestRerankModelV1RerankModelsTestPostErrors[keyof TestRerankModelV1RerankModelsTestPostErrors];

export type TestRerankModelV1RerankModelsTestPostResponses = {
    /**
     * Successful Response
     */
    200: RerankTestResult;
};

export type TestRerankModelV1RerankModelsTestPostResponse = TestRerankModelV1RerankModelsTestPostResponses[keyof TestRerankModelV1RerankModelsTestPostResponses];

export type DeleteRerankModelV1RerankModelsModelIdDeleteData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Model Id
         */
        model_id: string;
    };
    query?: never;
    url: '/v1/rerank-models/{model_id}';
};

export type DeleteRerankModelV1RerankModelsModelIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRerankModelV1RerankModelsModelIdDeleteError = DeleteRerankModelV1RerankModelsModelIdDeleteErrors[keyof DeleteRerankModelV1RerankModelsModelIdDeleteErrors];

export type UpdateRerankModelV1RerankModelsModelIdPostData = {
    body: RerankModelUpdate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Model Id
         */
        model_id: string;
    };
    query?: never;
    url: '/v1/rerank-models/{model_id}';
};

export type UpdateRerankModelV1RerankModelsModelIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateRerankModelV1RerankModelsModelIdPostError = UpdateRerankModelV1RerankModelsModelIdPostErrors[keyof UpdateRerankModelV1RerankModelsModelIdPostErrors];

export type UpdateRerankModelV1RerankModelsModelIdPostResponses = {
    /**
     * Successful Response
     */
    200: RerankModelOut;
};

export type UpdateRerankModelV1RerankModelsModelIdPostResponse = UpdateRerankModelV1RerankModelsModelIdPostResponses[keyof UpdateRerankModelV1RerankModelsModelIdPostResponses];

export type BindCollectionRerankerV1CollectionsCollectionIdRerankerPostData = {
    body: CollectionRerankerBind;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/collections/{collection_id}/reranker';
};

export type BindCollectionRerankerV1CollectionsCollectionIdRerankerPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BindCollectionRerankerV1CollectionsCollectionIdRerankerPostError = BindCollectionRerankerV1CollectionsCollectionIdRerankerPostErrors[keyof BindCollectionRerankerV1CollectionsCollectionIdRerankerPostErrors];

export type BindCollectionRerankerV1CollectionsCollectionIdRerankerPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetChunkV1ChunksChunkIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Chunk Id
         */
        chunk_id: string;
    };
    query?: never;
    url: '/v1/chunks/{chunk_id}';
};

export type GetChunkV1ChunksChunkIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetChunkV1ChunksChunkIdGetError = GetChunkV1ChunksChunkIdGetErrors[keyof GetChunkV1ChunksChunkIdGetErrors];

export type GetChunkV1ChunksChunkIdGetResponses = {
    /**
     * Successful Response
     */
    200: ChunkDetail;
};

export type GetChunkV1ChunksChunkIdGetResponse = GetChunkV1ChunksChunkIdGetResponses[keyof GetChunkV1ChunksChunkIdGetResponses];

export type ListDocumentChunksV1DocumentsDocIdChunksGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Doc Id
         */
        doc_id: string;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/v1/documents/{doc_id}/chunks';
};

export type ListDocumentChunksV1DocumentsDocIdChunksGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListDocumentChunksV1DocumentsDocIdChunksGetError = ListDocumentChunksV1DocumentsDocIdChunksGetErrors[keyof ListDocumentChunksV1DocumentsDocIdChunksGetErrors];

export type ListDocumentChunksV1DocumentsDocIdChunksGetResponses = {
    /**
     * Successful Response
     */
    200: ChunkList;
};

export type ListDocumentChunksV1DocumentsDocIdChunksGetResponse = ListDocumentChunksV1DocumentsDocIdChunksGetResponses[keyof ListDocumentChunksV1DocumentsDocIdChunksGetResponses];
